name: conda_env_test
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
    - ipython
    - numpy
    - tensorflow==2.3.0
    - tensorflow-gpu==2.3.1
    - matplotlib==3.3.2